services:
  homelab-control:
    build:
      context: ..
      dockerfile: ./webapp/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./config.yaml:/etc/homelab-control/config.yaml
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
