services:
  podman-manager:
    build:
      context: ..
      dockerfile: ./webapp/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./config.yaml:/etc/podman-manager/config.yaml
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
